### ISSUE TITLE
STUPID

### ISSUE THREAD

**Issue by mcnultyb** [fogleman/Minecraft#59]
**STUPID**, but good for a beginner who is trying to code! Good job *even though I can't run it*

**Comment by BertrandBordage** [comment]
Where is the “ban” button?

**Comment by mcnultyb** [comment]
Sorry... D: I didn't mean to be offensive...

**Comment by BertrandBordage** [comment]
Sorry @mcnultyb, I understand you were joking, but be aware that 189 people have received a mail entitled "STUPID" right now. I know this project is a toy, but the vast majority of people on GitHub use it as their daily work tool. We receive about a hundred mails each day for complex issues we have to reply. Nobody is used to spam on GitHub, that’s why I reacted that way.

You are new to open source. Take this as the first lesson ;)
People can be quite grumpy in open source because 98% of the feedback you’ll receive on a project is *yet* another problem to solve. After a few years, you can easily loose patience.

By the way, I appreciate your joviality :) Please continue learning open source, you won’t regret it! Just be nice to grumpy cats like me :p
